name: request-contracts

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch of the RequestNetwork/requestNetwork repository to build against
        default: master
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: repo-sha
        run: echo "sha=$(git ls-remote https://github.com/RequestNetwork/requestNetwork.git ${{ github.event.inputs.branch }} | cut -f 1 | cut -b -7)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: request-contracts
          platforms: linux/amd64,linux/arm64
          build-args: TAG=${{ steps.repo-sha.outputs.sha }}
          tags: requestnetwork/request-contracts:${{ steps.repo-sha.outputs.sha }},requestnetwork/request-contracts:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
