name: request-node

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the @requestnetwork/request-node NPM package to fetch (latest|next|version)
        default: next
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: npm-version
        run: echo "version=$(npm show @requestnetwork/request-node@${{ github.event.inputs.version }} version)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: request-node
          platforms: linux/amd64,linux/arm64
          build-args: REQUEST_NODE_VERSION=${{ steps.npm-version.outputs.version }}
          tags: requestnetwork/request-node:${{ steps.npm-version.outputs.version }},requestnetwork/request-node:${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
