on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the @requestnetwork/request-node NPM package to fetch (latest|next|version)
        default: latest
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: npm-version
        run: echo "::set-output name=version::$(npm show @requestnetwork/request-node@${{ github.event.inputs.version }} version)"
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: request-node
          build-args: VERSION=${{ steps.npm-version.outputs.version }}
          tags: requestnetwork/request-node:${{ steps.npm-version.outputs.version }},requestnetwork/request-node:${{ github.event.inputs.version }}
