name: request-ipfs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version (tag) of the ipfs/go-ipfs base Docker image to build from
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: request-ipfs
          build-args: IPFS_VERSION=${{ github.event.inputs.tag }}
          tags: requestnetwork/request-ipfs:${{ github.event.inputs.tag }},requestnetwork/request-ipfs:latest
