name: request-ipfs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version (tag) of the ipfs/go-ipfs base Docker image to build from
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: request-ipfs
          platforms: linux/amd64,linux/arm64
          build-args: IPFS_VERSION=${{ github.event.inputs.tag }}
          tags: requestnetwork/request-ipfs:${{ github.event.inputs.tag }},requestnetwork/request-ipfs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
