name: request-subgraph-storage

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch of the RequestNetwork/storage-subgraph repository to build against
        default: main
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: repo-sha
        run: echo "::set-output name=sha::$(git ls-remote https://github.com/RequestNetwork/storage-subgraph.git ${{ github.event.inputs.branch }} | cut -f 1 | cut -b -7)"
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          context: request-subgraph-storage
          build-args: STORAGE_SUBGRAPH_TAG=${{ steps.repo-sha.outputs.sha }}
          tags: requestnetwork/request-subgraph-storage:${{ steps.repo-sha.outputs.sha }},requestnetwork/request-subgraph-storage:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max